"""HTML report rendering.

Every result object in ``ml-xray`` can emit a self-contained HTML section. This
module holds the :mod:`jinja2` templates and helpers that stitch those sections
into a single file with no external asset requests (all CSS is inlined). Phase 1
renders the lint section; the slices/embed sections are wired in later phases.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from jinja2 import Environment, select_autoescape

if TYPE_CHECKING:  # pragma: no cover
    from .lint.linter import LintReport

__all__ = ["lint_report_html", "render_report"]

_ENV = Environment(autoescape=select_autoescape(["html", "xml"]))

_BASE_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0; padding: 2rem; line-height: 1.5;
  color: #1a1a1a; background: #ffffff;
}
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.15rem; margin: 2rem 0 .5rem; }
.subtitle { color: #666; margin: 0 0 1.5rem; font-size: .9rem; }
.summary { display: flex; gap: .75rem; flex-wrap: wrap; margin: 1rem 0 1.5rem; }
.pill {
  border-radius: 999px; padding: .35rem .9rem; font-size: .85rem; font-weight: 600;
  border: 1px solid rgba(0,0,0,.1);
}
.pill.error { background: #fdecea; color: #b3261e; }
.pill.warn { background: #fff4e5; color: #9a6700; }
.pill.info { background: #e8f0fe; color: #1a4fb4; }
.pill.ok { background: #e6f4ea; color: #1e7d34; }
table { border-collapse: collapse; width: 100%; font-size: .88rem; }
th, td { text-align: left; padding: .5rem .6rem; border-bottom: 1px solid rgba(0,0,0,.08);
  vertical-align: top; }
th { font-weight: 600; color: #444; border-bottom: 2px solid rgba(0,0,0,.15); }
.sev { font-weight: 700; white-space: nowrap; }
.sev.ERROR { color: #b3261e; }
.sev.WARN { color: #9a6700; }
.sev.INFO { color: #1a4fb4; }
.col { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .82rem; }
.detail { color: #666; font-size: .8rem; }
.empty { color: #1e7d34; font-weight: 600; }
footer { margin-top: 2.5rem; color: #999; font-size: .78rem; }
@media (prefers-color-scheme: dark) {
  body { color: #e8e8e8; background: #16181c; }
  .subtitle, .detail, th { color: #a0a0a0; }
  th, td { border-color: rgba(255,255,255,.1); }
  .pill { border-color: rgba(255,255,255,.12); }
  .pill.error { background: #3a1512; color: #f2a99f; }
  .pill.warn { background: #3a2c10; color: #f0cf7a; }
  .pill.info { background: #12233f; color: #9dbdf5; }
  .pill.ok, .empty { background: #12331d; color: #8fd6a2; }
}
"""

_LINT_TEMPLATE = _ENV.from_string("""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ml-xray lint report</title>
<style>{{ css }}</style></head>
<body>
<h1>ml-xray &mdash; dataset lint report</h1>
<p class="subtitle">
  {{ meta.n_rows }} rows &times; {{ meta.n_columns }} columns
  {% if meta.target %}&middot; target <code>{{ meta.target }}</code>{% endif %}
  {% if meta.task %}&middot; task {{ meta.task }}{% endif %}
  {% if meta.has_split %}&middot; split-aware{% endif %}
</p>

<div class="summary">
  <span class="pill error">ERROR {{ counts.ERROR }}</span>
  <span class="pill warn">WARN {{ counts.WARN }}</span>
  <span class="pill info">INFO {{ counts.INFO }}</span>
  {% if counts.ERROR == 0 %}<span class="pill ok">gate: pass</span>
  {% else %}<span class="pill error">gate: fail</span>{% endif %}
</div>

<h2>Findings</h2>
{% if findings %}
<table>
  <thead><tr>
    <th>Severity</th><th>Check</th><th>Column</th><th>Message</th><th>Rows</th>
  </tr></thead>
  <tbody>
  {% for f in findings %}
    <tr>
      <td class="sev {{ f.severity.name }}">{{ f.severity.name }}</td>
      <td>{{ f.check }}</td>
      <td class="col">{{ f.column if f.column is not none else "—" }}</td>
      <td>{{ f.message }}<div class="detail">{{ f.detail_summary }}</div></td>
      <td class="detail">{{ f.row_count }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p class="empty">No issues found. &#10003;</p>
{% endif %}

<footer>Generated by ml-xray &bull; checks: {{ meta.checks | join(", ") }}</footer>
</body></html>
""")


def _finding_view(f) -> dict:
    """Prepare a finding for the template (compact detail + row count)."""
    keys = [k for k in f.detail if k != "kind"]
    parts = []
    for k in keys[:4]:
        v = f.detail[k]
        if isinstance(v, float):
            parts.append(f"{k}={v:.4g}")
        elif isinstance(v, (int, str)):
            parts.append(f"{k}={v}")
    return {
        "severity": f.severity,
        "check": f.check,
        "column": f.column,
        "message": f.message,
        "detail_summary": " · ".join(parts),
        "row_count": f"{len(f.rows)} rows" if f.rows else "",
    }


def lint_report_html(report: LintReport) -> str:
    """Render a :class:`~ml_xray.lint.linter.LintReport` to an HTML string.

    Parameters
    ----------
    report : LintReport
        The report to render.

    Returns
    -------
    str
        A complete, self-contained HTML document.
    """
    ordered = report.worst(n=len(report.findings)) if report.findings else []
    views = [type("V", (), v) for v in map(_finding_view, ordered)]
    return _LINT_TEMPLATE.render(
        css=_BASE_CSS,
        meta=report.meta,
        counts=report.counts(),
        findings=views,
    )


def render_report(*sections: str, title: str = "ml-xray report") -> str:
    """Stitch pre-rendered HTML sections into one document.

    Placeholder for the Phase 4 unified report that combines lint, slices, and
    embed sections into a single file.

    Parameters
    ----------
    *sections : str
        Pre-rendered HTML fragments.
    title : str
        Document title.

    Raises
    ------
    NotImplementedError
        Always -- the unified multi-section report is Phase 4.
    """
    raise NotImplementedError(
        "TODO(phase 4): combine lint/slices/embed sections into one HTML report."
    )
