"""HTML report rendering.

Every result object in ``ml-xray`` can emit a self-contained HTML section. This
module holds the :mod:`jinja2` templates and helpers that render each section
(lint / slices / embed) and stitch them into a single file with no external asset
requests (all CSS is inlined). Optional matplotlib figures are produced lazily and
degrade to a clear error when no plotting backend is installed.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from jinja2 import Environment, select_autoescape

if TYPE_CHECKING:  # pragma: no cover
    from .embed.diff import EmbedDiffReport
    from .lint.linter import LintReport
    from .slices.finder import SliceReport

__all__ = [
    "lint_report_html",
    "slice_report_html",
    "embed_report_html",
    "render_report",
    "lint_section",
    "slice_section",
    "embed_section",
    "slice_bar_figure",
    "embed_projection_figure",
]

_ENV = Environment(autoescape=select_autoescape(["html", "xml"]))

_BASE_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0; padding: 2rem; line-height: 1.5;
  color: #1a1a1a; background: #ffffff;
}
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.15rem; margin: 2rem 0 .5rem; }
.subtitle { color: #666; margin: 0 0 1.5rem; font-size: .9rem; }
.summary { display: flex; gap: .75rem; flex-wrap: wrap; margin: 1rem 0 1.5rem; }
.pill {
  border-radius: 999px; padding: .35rem .9rem; font-size: .85rem; font-weight: 600;
  border: 1px solid rgba(0,0,0,.1);
}
.pill.error { background: #fdecea; color: #b3261e; }
.pill.warn { background: #fff4e5; color: #9a6700; }
.pill.info { background: #e8f0fe; color: #1a4fb4; }
.pill.ok { background: #e6f4ea; color: #1e7d34; }
.pill.metric { background: #eee; color: #333; }
table { border-collapse: collapse; width: 100%; font-size: .88rem; }
th, td { text-align: left; padding: .5rem .6rem; border-bottom: 1px solid rgba(0,0,0,.08);
  vertical-align: top; }
th { font-weight: 600; color: #444; border-bottom: 2px solid rgba(0,0,0,.15); }
.sev { font-weight: 700; white-space: nowrap; }
.sev.ERROR { color: #b3261e; }
.sev.WARN { color: #9a6700; }
.sev.INFO { color: #1a4fb4; }
.neg { color: #b3261e; font-weight: 600; }
.col { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .82rem; }
.detail { color: #666; font-size: .8rem; }
.empty { color: #1e7d34; font-weight: 600; }
figure { margin: 1rem 0; }
figure img { max-width: 100%; height: auto; }
footer { margin-top: 2.5rem; color: #999; font-size: .78rem; }
@media (prefers-color-scheme: dark) {
  body { color: #e8e8e8; background: #16181c; }
  .subtitle, .detail, th { color: #a0a0a0; }
  th, td { border-color: rgba(255,255,255,.1); }
  .pill { border-color: rgba(255,255,255,.12); }
  .pill.error { background: #3a1512; color: #f2a99f; }
  .pill.warn { background: #3a2c10; color: #f0cf7a; }
  .pill.info { background: #12233f; color: #9dbdf5; }
  .pill.ok, .empty { background: #12331d; color: #8fd6a2; }
  .pill.metric { background: #23262c; color: #cfd3da; }
}
"""

_DOCUMENT = _ENV.from_string("""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title>
<style>{{ css }}</style></head>
<body>
<h1>{{ title }}</h1>
{{ body }}
<footer>Generated by ml-xray</footer>
</body></html>
""")


def _document(title: str, body: str) -> str:
    # `body` is already-rendered, trusted HTML from our own section templates.
    from markupsafe import Markup

    return _DOCUMENT.render(title=title, css=_BASE_CSS, body=Markup(body))


# --------------------------------------------------------------------------
# Lint section
# --------------------------------------------------------------------------

_LINT_SECTION = _ENV.from_string("""<p class="subtitle">
  {{ meta.n_rows }} rows &times; {{ meta.n_columns }} columns
  {% if meta.target %}&bull; target <code>{{ meta.target }}</code>{% endif %}
  {% if meta.task %}&bull; task {{ meta.task }}{% endif %}
  {% if meta.has_split %}&bull; split-aware{% endif %}
</p>
<div class="summary">
  <span class="pill error">ERROR {{ counts.ERROR }}</span>
  <span class="pill warn">WARN {{ counts.WARN }}</span>
  <span class="pill info">INFO {{ counts.INFO }}</span>
  {% if counts.ERROR == 0 %}<span class="pill ok">gate: pass</span>
  {% else %}<span class="pill error">gate: fail</span>{% endif %}
</div>
<h2>Lint findings</h2>
{% if findings %}
<table>
  <thead><tr>
    <th>Severity</th><th>Check</th><th>Column</th><th>Message</th><th>Rows</th>
  </tr></thead>
  <tbody>
  {% for f in findings %}
    <tr>
      <td class="sev {{ f.severity.name }}">{{ f.severity.name }}</td>
      <td>{{ f.check }}</td>
      <td class="col">{{ f.column if f.column is not none else "—" }}</td>
      <td>{{ f.message }}<div class="detail">{{ f.detail_summary }}</div></td>
      <td class="detail">{{ f.row_count }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p class="empty">No issues found. &#10003;</p>
{% endif %}
""")


def _finding_view(f) -> type:
    keys = [k for k in f.detail if k != "kind"]
    parts = []
    for k in keys[:4]:
        v = f.detail[k]
        if isinstance(v, float):
            parts.append(f"{k}={v:.4g}")
        elif isinstance(v, (int, str)):
            parts.append(f"{k}={v}")
    view = {
        "severity": f.severity,
        "check": f.check,
        "column": f.column,
        "message": f.message,
        "detail_summary": " · ".join(parts),
        "row_count": f"{len(f.rows)} rows" if f.rows else "",
    }
    return type("V", (), view)


def lint_section(report: LintReport) -> str:
    """Render the lint report as an HTML body fragment (no ``<html>`` wrapper)."""
    ordered = report.worst(n=len(report.findings)) if report.findings else []
    views = [_finding_view(f) for f in ordered]
    return _LINT_SECTION.render(meta=report.meta, counts=report.counts(), findings=views)


def lint_report_html(report: LintReport) -> str:
    """Render a :class:`~ml_xray.lint.linter.LintReport` to a full HTML document."""
    return _document("ml-xray — dataset lint report", lint_section(report))


# --------------------------------------------------------------------------
# Slice section
# --------------------------------------------------------------------------

_SLICE_SECTION = _ENV.from_string("""<div class="summary">
  <span class="pill metric">metric: {{ metric }}</span>
  <span class="pill metric">baseline: {{ "%.4g"|format(baseline) }}</span>
  <span class="pill {{ 'error' if slices else 'ok' }}">{{ slices|length }} slices</span>
</div>
<h2>Underperforming slices</h2>
{% if slices %}
<table>
  <thead><tr>
    <th>Slice</th><th>Support</th><th>Metric</th><th>Baseline</th><th>Delta</th><th>p-value</th>
  </tr></thead>
  <tbody>
  {% for s in slices %}
    <tr>
      <td class="col">{{ s.describe() }}</td>
      <td>{{ s.support }}</td>
      <td>{{ "%.4g"|format(s.metric_value) }}</td>
      <td>{{ "%.4g"|format(s.baseline) }}</td>
      <td class="{{ 'neg' if s.delta < 0 else '' }}">{{ "%+.4g"|format(s.delta) }}</td>
      <td class="detail">{{ "%.3g"|format(s.p_value) }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p class="empty">No significant underperforming slices found. &#10003;</p>
{% endif %}
""")


def slice_section(report: SliceReport) -> str:
    """Render a slice report as an HTML body fragment."""
    return _SLICE_SECTION.render(
        metric=report.metric, baseline=report.baseline, slices=report.slices
    )


def slice_report_html(report: SliceReport) -> str:
    """Render a :class:`~ml_xray.slices.finder.SliceReport` to a full HTML document."""
    return _document("ml-xray — slice discovery report", slice_section(report))


# --------------------------------------------------------------------------
# Embed section
# --------------------------------------------------------------------------

_EMBED_SECTION = _ENV.from_string("""<div class="summary">
  <span class="pill metric">k = {{ k }}</span>
  <span class="pill metric">neighbor overlap: {{ "%.3f"|format(neighbor_overlap) }}</span>
  <span class="pill metric">cluster stability (ARI): {{ "%.3f"|format(cluster_stability) }}</span>
  <span class="pill metric">mean drift: {{ "%.3f"|format(mean_drift) }}</span>
</div>
<h2>Embedding diff</h2>
<p class="subtitle">{{ n_points }} points compared. Overlap 1.0 = local structure
fully preserved; 0.0 = neighborhoods entirely changed.</p>
{% if image %}<figure><img src="{{ image }}" alt="before/after projection"></figure>{% endif %}
<h2>Top movers</h2>
{% if movers %}
<table>
  <thead><tr><th>Rank</th><th>Id</th><th>Neighborhood drift</th></tr></thead>
  <tbody>
  {% for m in movers %}
    <tr><td>{{ loop.index }}</td><td class="col">{{ m.id }}</td>
        <td class="neg">{{ "%.3f"|format(m.drift) }}</td></tr>
  {% endfor %}
  </tbody>
</table>
{% else %}<p class="empty">No movers.</p>{% endif %}
""")


def embed_section(report: EmbedDiffReport, *, image: str | None = None) -> str:
    """Render an embedding-diff report as an HTML body fragment.

    Parameters
    ----------
    report : EmbedDiffReport
        The report to render.
    image : str, optional
        A ``data:`` URI for the projection scatter to embed inline.
    """
    import numpy as np

    drift = report.per_point_drift
    id_to_drift = {rid: float(drift[i]) for i, rid in enumerate(report.ids)}
    movers = [
        type("M", (), {"id": m, "drift": id_to_drift.get(m, 0.0)}) for m in report.movers[:25]
    ]
    mean_drift = float(np.mean(drift)) if drift.size else float("nan")
    return _EMBED_SECTION.render(
        k=report.k,
        neighbor_overlap=report.neighbor_overlap,
        cluster_stability=report.cluster_stability,
        mean_drift=mean_drift,
        n_points=int(drift.size),
        movers=movers,
        image=image,
    )


def embed_report_html(report: EmbedDiffReport, *, with_projection: bool = True) -> str:
    """Render an :class:`~ml_xray.embed.diff.EmbedDiffReport` to a full HTML document.

    Parameters
    ----------
    report : EmbedDiffReport
        The report to render.
    with_projection : bool
        Whether to embed the before/after projection scatter (requires
        matplotlib; silently omitted if unavailable).
    """
    image = None
    if with_projection:
        image = _projection_data_uri(report)
    return _document("ml-xray — embedding diff report", embed_section(report, image=image))


# --------------------------------------------------------------------------
# Unified report
# --------------------------------------------------------------------------


def render_report(*sections: str, title: str = "ml-xray report") -> str:
    """Stitch pre-rendered HTML sections into one self-contained document.

    Parameters
    ----------
    *sections : str
        Pre-rendered HTML fragments (e.g. from :func:`lint_section`,
        :func:`slice_section`, :func:`embed_section`).
    title : str
        Document title.

    Returns
    -------
    str
        A complete HTML document combining the sections.
    """
    return _document(title, "\n<hr>\n".join(s for s in sections if s))


# --------------------------------------------------------------------------
# Optional matplotlib figures
# --------------------------------------------------------------------------


def _require_matplotlib():
    from ._optional import optional_import

    plt = optional_import("matplotlib")
    if plt is None:
        raise ImportError('Plotting needs matplotlib. Install it with: pip install "ml-xray[viz]"')
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as pyplot

    return pyplot


def slice_bar_figure(report: SliceReport):
    """Return a matplotlib bar chart of the worst slices' deltas."""
    plt = _require_matplotlib()
    slices = report.slices[:15][::-1]
    labels = [s.describe() for s in slices]
    deltas = [s.delta for s in slices]
    fig, ax = plt.subplots(figsize=(8, max(2, 0.4 * len(slices) + 1)))
    ax.barh(labels, deltas, color=["#b3261e" if d < 0 else "#1e7d34" for d in deltas])
    ax.axvline(0, color="#888", linewidth=0.8)
    ax.set_xlabel(f"delta vs baseline ({report.metric})")
    ax.set_title("Worst-performing slices")
    fig.tight_layout()
    return fig


def embed_projection_figure(report: EmbedDiffReport, *, seed: int = 0):
    """Return a linked before/after 2D scatter of the two embedding spaces."""
    plt = _require_matplotlib()
    if report._emb_a is None or report._emb_b is None:
        raise RuntimeError("source embeddings were not retained on the report")
    from .embed.project import project_2d

    proj_a, proj_b = project_2d(
        report._emb_a, report._emb_b, projector=report_projector(report), seed=seed
    )
    drift = report.per_point_drift
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5), sharex=True, sharey=True)
    for ax, proj, title in ((axes[0], proj_a, "A (before)"), (axes[1], proj_b, "B (after)")):
        sc = ax.scatter(proj[:, 0], proj[:, 1], c=drift, cmap="magma", s=12)
        ax.set_title(title)
        ax.set_xticks([])
        ax.set_yticks([])
    fig.colorbar(sc, ax=axes, label="neighborhood drift", fraction=0.046)
    fig.suptitle("Embedding spaces (colored by per-point drift)")
    return fig


def report_projector(report: EmbedDiffReport) -> str:
    """Best-effort projector choice for a report (kept simple: auto)."""
    return "auto"


def _projection_data_uri(report: EmbedDiffReport) -> str | None:
    """Render the projection figure to a base64 PNG data URI, or None if unavailable."""
    try:
        fig = embed_projection_figure(report)
    except (ImportError, RuntimeError):
        return None
    import base64
    import io

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight")
    import matplotlib.pyplot as plt

    plt.close(fig)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"
